#' Run AI Segmentation Workflow
#'
#' This function executes the full AI segmentation workflow, including reading input files, merging segments, BAF processing, and writing results.
#'
#' @param seg Path to the GATK segment file.
#' @param cov Path to the GATK denoised coverage count file.
#' @param cr Path to the GATK denoised coverage ratio file.
#' @param ai Path to the BAF file or allelic count file.
#' @param ai_pon Path to PON Rdata. AI panel of normal generated by \code{PONAIprocess}.
#' @param gender Character, "male" or "female"( if not available, set gender = "unknown" and run Runcheckgender function ahead to assign gender automatically) .
#' @param sampletype Character, "ff" or "ffpe".
#' @param out_dir Output directory path.
#' @param prefix Output file prefix.
#' @param covminvalleydrop minimum valley drop in the finding peaks of coverage track quality control, default is 0.1
#' @param covminproportion minimum proportion of peak in the finding peaks of coverage track quality control, default is 0.2
#' @param covminpeakdiff minimum peak difference in the finding peaks of coverage track quality control, default is 0.5
#' @param bafminproportion Minimum proportion of SNPs required for a BAF peak
#'   to be retained for MAF estimation; smaller peaks are excluded. default is 0.3
#' @param bafminseparationsd Minimum peak separation in units of fitted SD. Default 1.1.
#' @param covmadcutoff1 Numeric. Over this value will directly Fail qc. default is 0.6
#' @param covmadcutoff2 Numeric. Over this value, but lower than covmadcutoff1, if multiple peaks will fail the qc. default is 0.3
#' @param mafqcweightcutoff Numeric. Minimum SNP proportion in the main MAF peak
#'   required to pass MAF QC. Values below this cutoff fail QC. Default is 0.35.
#' @param mergeai Numeric, MAF difference threshold for merging segments (default: 0.05).
#' @param mergecov Numeric, CNV difference threshold for merging segments (default: 0.05).
#' @param snpmin Numeric, minimum SNPs for MAF segmentation (default: 4).
#' @param minsnpcov Numeric, minimum coverage of SNPs to included (default: 20).
#' @param maxgap Maximum gap size inside a bin. If exceed then start another bin.( default: 2000000)
#' @param snpnum SNP number in each bin.( default: 20 )
#' @param maxbinsize Maximum bin size.( default: 1000000 )
#' @param minbinsize Minimum bin size.( default: 500000 )
#' @param mergecovminsize Numeric, minimum size for GATK segment merge (default: 500000).
#' @param segmethod Character. Segmentation method to use: if \code{"merge"}, perform stepwise merging; if \code{"cbs"}, perform CBS (circular binary segmentation).
#' @param cbssmooth Character. If using the \code{"cbs"} segmentation method, set to \code{"yes"} to apply smoothing before segmentation, or \code{"no"} to skip smoothing. Default is yes.
#' @param aitype Character. Type of allelic imbalance data: \code{"gatk"} or \code{"other"} or \code{"dragen"}
#'   If \code{"GATK"}, the input must include columns \code{CONTIG}, \code{POSITION}, \code{ALT_COUNT}, \code{REF_COUNT}, \code{REF_NUCLEOTIDE}, and \code{ALT_NUCLEOTIDE}.
#'   If \code{"dragen"}, the input must include columns \code{contig}, \code{start}, \code{stop}, \code{refAllele}, \code{allele1}, \code{allele2}, \code{allele1Count}, \code{allele2Count}, \code{allele1AF}, and \code{allele2AF}.
#'   If \code{"other"}, the input must include columns \code{CONTIG}, \code{POSITION}, \code{ALT_COUNT}, \code{REF_COUNT}, \code{REF_NUCLEOTIDE}, and \code{ALT_NUCLEOTIDE}.
#' @return Invisibly returns the output file path.
#' @importFrom data.table fread
#' @importFrom dplyr filter mutate rowwise ungroup select
#' @importFrom stringr str_split
#' @importFrom tidyr unnest_wider
#' @export
RunAIsegmentation <- function(
    seg, cov, cr, ai, gender, out_dir, prefix, ai_pon, sampletype,
    covminvalleydrop = 0.1,
    covminproportion = 0.2,
    covminpeakdiff = 0.5,
    bafminproportion = 0.3,
    bafminseparationsd = 1.1,
    mergeai = 0.05,
    mergecov = 0.05,
    snpmin = 4,
    minsnpcov = 20,
    mergecovminsize = 500000,
    maxgap = 2000000,
    snpnum = 20,
    maxbinsize = 1000000,
    minbinsize = 500000,
    mafqcweightcutoff = 0.35,
    covmadcutoff1 = 0.6,
    covmadcutoff2 = 0.3,
    aitype="gatk",
    segmethod = "cbs",
    cbssmooth = "yes"


) {
  print("Start to run combined segmentation. Parameters are:")
  print(paste0("GATK Count file is: ", cov) )
  print(paste0("GATK CR file is: ", cr) )
  print(paste0("GATK Segment file is: ", seg) )
  print(paste0("Allelic count file type is :", aitype ))
  print(paste0("Allelic count file is: ", ai ))
  print(paste0("Allelic count PON file is: ", ai_pon))
  print(paste0("Gender is: ", gender ))
  print(paste0("Sample type is: ", sampletype ))
  print(paste0("mergecov is: ", mergecov))
  print(paste0("mergecovminsize is: ", mergecovminsize))
  print(paste0("mergeai is: ", mergeai))
  print(paste0("snpmin is: ", snpmin))
  print(paste0("minsnpcov is: ", minsnpcov))
  print(paste0("maxgap is: ", maxgap))
  print(paste0("snpnum is: ", snpnum))
  print(paste0("maxbinsize is: ", maxbinsize))
  print(paste0("minbinsize is: ",  minbinsize))
  print(paste0("segmethod is: ", segmethod))
  print(paste0("cbssmooth is: ", cbssmooth))
  print(paste0("covminvalleydrop is: ",  covminvalleydrop))
  print(paste0("covminproportion is: ", covminproportion))
  print(paste0("covminpeakdiff is: ", covminpeakdiff))
  print(paste0("bafminproportion is: ",  bafminproportion))
  print(paste0("bafminseparationsd is: ", bafminseparationsd))
  print(paste0("mafqcweightcutoff is: ", mafqcweightcutoff))
  print(paste0("covmadcutoff1 is: ", covmadcutoff1 ))
  print(paste0("covmadcutoff2 is: ", covmadcutoff2 ))



  # Read segment file
  seg_df <- data.table::fread(seg) %>%
    dplyr::mutate(size = End - Start)

  # Step 1: Gender check
  gender = tolower(gender)
  # Read coverage file
  lines <- readLines(cov)
  filtered_lines <- grep("^\\s*@", lines, invert = TRUE, value = TRUE)
  cov_df <- data.table::fread(text = filtered_lines)
  # Read denoised CR file
  cr_lines <- readLines(cr)
  cr_filtered_lines <- grep("^\\s*@", cr_lines, invert = TRUE, value = TRUE)
  cr_df <- data.table::fread(text = cr_filtered_lines)
  # Check consistency between GATK gender vs input gender
  # If different, use input gender and correct the CR file
  seg_df <- CheckGender(cov = cov_df, cr=cr_df, seg = seg_df,
                        gender = gender,
                        covminvalleydrop = covminvalleydrop,
                        covminproportion = covminproportion,
                        covminpeakdiff = covminpeakdiff)
  gender <- as.character(seg_df$pipeline_gender[1])

  # Read BAF file eg. GATK
  maf <- ReadAI(aitype = aitype, ballele = ai, minsnpcov = minsnpcov, gender = gender )
  maf <- maf %>%
    dplyr::filter(alt_count != 0 & ref_count != 0) %>%
    dplyr::filter(alt_count + ref_count >= minsnpcov)

  merge_seg <- seg_df

  # Step 2: Merge GATK segments by size
  if ( mergecovminsize < 1e+05) mergecovminsize <- 1e+05
  for (minsize in c(1000, 10000, 50000, seq(from = 100000, to = as.numeric(mergecovminsize), by = 100000))) {
    merge_seg <- merge_seg %>%
      dplyr::ungroup() %>%
      dplyr::filter(size >= minsize | Chromosome %in% c("X", "Y"))
    merge_seg <- CallMerge(data = merge_seg, AIorSeg = "Seg", snpmin = snpmin, mergeai = mergeai, mergecov = mergecov)
  }
  merge_seg <- subset(merge_seg, select = -Call)
  merge_seg <- merge_seg %>% dplyr::mutate(BreakpointSource = "GATK")


  ## Load AI PON file generated by PONAIprocess() function. It will load pon_ref and the theta_fit object
  load(ai_pon)
## seg_method "merge" and "cbs"
  # Step 4: Search for breakpoints in each segment
  combindAIseg <- lapply(seq_len(nrow(merge_seg)), function(x) {
    SearchBreakpoint(seg_row = merge_seg[x, ],
                     segmethod = segmethod,
                     cbssmooth = cbssmooth,
                     pon_ref = pon_ref,
                     maf = maf,
                     mergeai = mergeai,
                     snpmin = snpmin,
                     snpnum =  snpnum,
                     maxgap = maxgap,
                     maxbinsize = maxbinsize,
                     minbinsize = minbinsize,
                     minsnpcov = minsnpcov,
                     bafminproportion = bafminproportion,
                     bafminseparationsd = bafminseparationsd,
                     gender = gender,
                     out_dir = out_dir,
                     prefix = prefix)
  })
  combined_result <- do.call(rbind, combindAIseg)


  if( gender == "female"){
    combined_result <- combined_result %>%
      dplyr::filter( Chromosome != "Y")
  }

  # Step5: Add the median coverage of each segment for K estimation

  result <- EstimateK( combined_result, theta_fit, maf )
  chr_levels <- c(seq(1,22), "X","Y")
  result$Chromosome <- factor(result$Chromosome, levels = chr_levels)
  result <- result %>%
    dplyr::arrange( Chromosome, Start) %>%
    dplyr::mutate(MAF = ifelse( is.na(gmm_mean_corr), MAF, gmm_mean_corr)) %>%
    dplyr::select( - gmm_mean_corr)

  # Step 6: Add quality tag
  result <- result %>%
    dplyr::rowwise() %>%
    dplyr::mutate(FILTER = AddQualTag(
      Chromosome = Chromosome,
      MAF = MAF,
      MAF_gmm_weight = MAF_gmm_weight,
      MAF_Probes = MAF_Probes,
      MAF_gmm_G = MAF_gmm_G,
      snpmin = snpmin,
      balance_tag = balance_tag,
      cov_mad = cov_mad,
      cov_peak_count = cov_peak_count,
      covmadcutoff1 = covmadcutoff1,
      covmadcutoff2 = covmadcutoff2,
      mafqcweightcutoff = mafqcweightcutoff,
      gender = gender
    ))

  # Step 7: Write output
  outFile <- file.path(out_dir, paste0(prefix, "_GATK_AI_segment.tsv"))
  write.table(result, file = outFile, sep = "\t", quote = FALSE, row.names = FALSE)

  invisible(outFile)
}
